"""Add wager_amount to BetParticipation

Revision ID: 7bccc35e2736
Revises: 41002d4f6c66
Create Date: 2025-11-13 15:02:33.492353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bccc35e2736'
down_revision = '41002d4f6c66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_participation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wager_amount', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bet_participation', schema=None) as batch_op:
        batch_op.drop_column('wager_amount')

    # ### end Alembic commands ###
